### ISSUE TITLE
'list_transforms" returns a blank list

### ISSUE THREAD

**Issue by Nick-Harvey** [rasgointelligence/RasgoQL#18]
I can successfully connect to the DW and run 'rql.list_tables.()`. However, when I run `rql.list_transforms()` I get an empty list back. 

In:
```
# List transforms
rql.list_transforms()
```
Out:
```
[]
```

RasgoQL version - 0.0.2

**Comment by griffatrasgo** [comment]
Thank you for reporting. This was a bug in the `rasgotransforms` package, which is a dependency. I know the maintainer of the package and asked him for a favor. He's a great  guy and fixed it right away. 
This bug can be fixed by running `pip install rasgotransforms --upgrade` (or installing version 0.0.2 or above)
