### ISSUE TITLE
New DB Request | MySQL

### ISSUE THREAD

**Issue by pjaol** [rasgointelligence/RasgoQL#46]
Looks very interesting, would love to see a mysql driver / transformer

**Comment by griffatrasgo** [comment]
Thanks for the request @pjaol . We are definitely planning to expand support to more DBs. MySQL is currently #3 on the backlog, which probably puts it a few weeks out. If you have a business use case or army of users that need it sooner, let us know and we'll see if we can help you out.
Otherwise, I'll ping you when we're ready to release to see if you'd like early access to an alpha.
